### ISSUE TITLE
v0.156.1 does not work right

### ISSUE THREAD

**Issue by mehmetkursataydin** [pirafrank/zed_unofficial_win_builds#1] opened 2024-10-14 18:58 UTC
Process runs but no GUI

**Comment by pirafrank** [comment] 2024-10-14 19:12
confirm. will try to investigate.

**Comment by pirafrank** [comment] 2024-10-14 19:18
it works actually. check if you have any other running zed instance, maybe an older version of it.

![image](https://github.com/user-attachments/assets/20363d15-09e0-43f6-a5f2-7a777e02d27d)

**Comment by pirafrank** [comment] 2024-10-14 19:21
`v0.155.2` works. you can use that in the meantime.

**Comment by pirafrank** [comment] 2024-10-14 19:35
further investigation shows that something has been broken since `v0.156.x`. Later versions affected, too. I will try to find root cause by diff in sources in their repo.

**Comment by pirafrank** [comment] 2024-10-18 09:00
Pre-release versions of `0.158.x` work again, tested with `v0.158.1` ([link](https://github.com/pirafrank/zed_unofficial_win_builds/releases/tag/v0.158.1-pre)). Broken versions are those in the `0.156.x` - `0.157.y` range.

I've edited the pipeline to add `.pdb` files in newer builds to help with debugging in case this happens again. Closing this issue for now.

**Closed as completed by pirafrank** 2024-10-18 09:00 UTC
